[theme]
theme = "native"
[theme.overrides]
separator = ""

[icons]
icons = "material-nf"



#

[[block]]
block = "focused_window"
format = "<span font_size='12pt' font_weight='heavy' color='skyblue'>$title.str(0,200)</span> |"
[[block.click]]
button = "left"
cmd = "swaymsg gaps inner current toggle 30"
[block.theme_overrides]
idle_bg = "#00000000"


[[block]]
block = "weather"
format = """ \
    <span baseline_shift='2pt' font_size='13pt'>$icon</span> \
    <span baseline_shift='4pt'>$weather_verbose</span> \
    <span color='cyan'>$temp $humidity<span font_size='90%' baseline_shift='superscript'>ğŸŒ¢</span> \
    $wind<span font_size='90%' baseline_shift='superscript'>~m/s</span></span> \
"""
service = { name = "openweathermap", api_key = "212dbd65c18ac42f9d884dde9b49692a", city_id = "7530791", units = "metric" }
[[block.click]]
button = "left"
cmd = "~/.config/sway/wsempty.py gnome-weather"
[block.icons_overrides]
weather_sun = "â˜€ï¸"
weather_rain = "ğŸŒ§ï¸"
weather_clouds = "â˜ï¸"
weather_thunder = "â›ˆï¸"
weather_snow = "â„ï¸"


[[block]]
block = "time"
format = """\
    <span baseline_shift='3pt' color='gray'>%a \
    <span color='white' font_size='12pt'>%e\
    </span>.%b </span>\
    <span font_size='18pt'>%H:%M</span>\
"""
timezone = "Europe/Warsaw"
interval = 60
icons_format = " "
[[block.click]]
button = "left"
cmd = "~/.config/sway/wsempty.py alacritty -e 'calcurse'"





